---
# tasks file for php
- include_vars: xenial.yml
  when: ansible_distribution_version == "16.04"

- include_vars: trusty.yml
  when: ansible_distribution_version == "14.04"

- include_vars: precise.yml
  when: ansible_distribution_version == "12.04"

- include: php7_ppa.yml
  when: ansible_distribution_version == "14.04" or ansible_distribution_version == "12.04"

- name: Install php software
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{php_packages}}"

- name: PHP info
  copy:
    src: php-info.php
    dest: "{{nginx_path}}"
    owner: www-data
    group: www-data

#ToDo PHP Activation in nginx
#Changed in 14.04 and higher
