---
# tasks file for php
- name: Install php software
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - php
    - php-mysql
    - php-curl
    - php-gd
    - mysql-client
    - php-mbstring
    - php-xml
    - php-xmlrpc
  when: ansible_distribution_version == "16.04"

- name: Install php software
  apt:
    name: "{{item}}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - php5
    - php5-mysql
    - php5-curl
    - php5-gd
    - mysql-client
  when: ansible_distribution_version == "14.04" or ansible_distribution_version == "12.04"

- name: PHP info
  copy:
    src: php-info.php
    dest: /var/www/html/php-info.php
    owner: www-data
    group: www-data
  when: ansible_distribution_version == "16.04"

- name: PHP info
  copy:
    src: php-info.php
    dest: /var/www/php-info.php
    owner: www-data
    group: www-data
  when: ansible_distribution_version == "14.04" or ansible_distribution_version == "12.04"

- name: Activate php
  blockinfile:
    content: |
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                # With php7.0-fpm:
                fastcgi_pass unix:/run/php/php7.0-fpm.sock;
              }
    dest: /etc/nginx/sites-available/default
    insertafter: "pass the PHP scripts to FastCGI server"
  notify: reload nginx
